### ISSUE TITLE
Sugestia poprawy tłumaczenia ciągu: MOD_QUICKICON_MODULE_MANAGER

### ISSUE THREAD

**Issue by Rogackis** [JoomlaPolska/jezyk-J4#1]
### Co należy poprawić / skorygować

MOD_QUICKICON_MODULE_MANAGER="Moduły: Moduły"

### Gdzie jest wyświetlany ciąg językowy (frontend/backend)

administrator\language\pl-PL\mod_quickicon.ini

### Jakie byłoby lepsze tłumaczenie / oznaczenie

MOD_QUICKICON_MODULE_MANAGER="Moduły"

### Wersja Joomla i wersja polskiego pliku językowego

 Aktualnie zainstalowana wersja Joomla! to "‎4.0.2" ‎4.0.2
 Aktualnie zainstalowana wersja  tłumaczenia to Polski (PL) 4.0.2.2

**Comment by zwiastunsw** [comment]
Naprawione
