### ISSUE TITLE
Instalacja jezyka z Githuba - zła wersja po instalacji

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#12]
### Co trzeba zmienić/skorygować?

Opis po instalacji "Joomla! - pakiet języka polskiego - 3.9.28"

### Jakie tłumaczenie byłoby lepsze

Joomla! - pakiet języka polskiego - 4.0.2
lub
Joomla! - pakiet języka polskiego dla wersji 4

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
![image](https://user-images.githubusercontent.com/28987360/131315593-de57b997-e87c-45e2-840c-2400a261160c.png)

### Wersja Joomla! i wersja polskiego pakietu językowego
pl-PL_joomla_lang_full_4.0.2v2

### Dodatkowe informacje

Zrezygnowałbym z opisu wersji, ponieważ ręczne instalacje odbywają się przez osoby, które ściągają wersje jak np. z Githuba.
1) są bardziej zaawansowane mają wersje opisana w pliku pl-PL_joomla_lang_full_4.0.2v2
2) łatwo jest zapomnieć zmienić w tym miejscu wersje.
3) gdy wyjdzie wersja 4.1 po prostu zmieni się to raz.

**Comment by zwiastunsw** [comment]
Słusznie, poprawimy. :)
