### ISSUE TITLE
Raportowanie błędów - zaplecze

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#13]
### Co trzeba zmienić/skorygować?
**COM_CONFIG_FIELD_VALUE_SYSTEM_DEFAULT** - "Szczegóły połączenia FTP"

### Jakie tłumaczenie byłoby lepsze
**COM_CONFIG_FIELD_VALUE_SYSTEM_DEFAULT** - "Podstawowe"

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

Zaplecze/ Serwer

### Wersja Joomla! i wersja polskiego pakietu językowego
pl-PL_joomla_lang_full_4.0.2v2

**Comment by zwiastunsw** [comment]
w oryginale jest Default system, czyli "Domyślne systemu". Dzięki
