### ISSUE TITLE
Workflow - Basic

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#14]
witam,
Chciałbym, aby jak ma nazywać się Workflow zdecydowała społeczność.
Najpierw były **TOKI** 
Teraz są **PROCESY** 
A Workflow to **PRZEPŁYW** 
Workflow również dobrze może być **WORKFLOW** w softach nikt tego nie tłumaczy, tak samo jak Load Balancer i kilkunastu innych wyrażeń. 

Moim zdaniem temat powinien być przedyskutowany w szerszym gronie, tak aby zwykły użytkownik wiedział, o co chodzi, a nie musiał dopytywać google. 

Zwykła ankieta utworzona przez Google Ankiety rozesłać do Adminów JUGów użyć Facebooka / forum / Maila 
I będzie wiadomo, które tłumaczenie jest najbardziej odpowiednie.

A w międzyczasie do poprawy.

### Co trzeba zmienić/skorygować?
COM_WORKFLOW_BASIC_WORKFLOW - Zmień proces pracy

### Jakie tłumaczenie byłoby lepsze
COM_WORKFLOW_BASIC_WORKFLOW - Podstawowy proces pracy

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![image](https://user-images.githubusercontent.com/28987360/131319496-c4e6b0c8-1f10-42ce-8d05-b6f8d3d4a8e9.png)

### Wersja Joomla! i wersja polskiego pakietu językowego

pl-PL_joomla_lang_full_4.0.2v2

**Comment by zwiastunsw** [comment]
Workflow to proces pracy, tok pracy, przepływ czynności. 
1. Głosowaniem takie kwestie trudno rozstrzygać. Zbyt wiele czynników trzeba wziąć pod uwagę. 
2. Zadaniem tłumaczy jest znaleźć najlepsze możliwe polskie odpowiedniki. Czasem to zadanie prawie niewykonalne (prawdopodobnie jest tak z Load Balancer - stąd w opisie zostawiliśmy i ten angielski termin, żeby nie było nieporozumień)
3. Odbiorcą tłumaczenia nie są ani tylko, ani nawet przede wszystkim profesjonaliści, dla których język angielski może i nie stanowi problemu). Dla pani Zosi i pana Jacka "równoważenie obciążenia" coś mówi, Load balancer nie mówi nic.
4. "Procesy pracy" pojawiły się jako propozycja najpóźniej. Oznacza dokładnie to samo co  "toki pracy" - ale słowo jest "zwyklejsze", popularne, więc łatwiejsze do zrozumienia.
5. Też mnie ten "Zmień proces pracy" raził, ale w natłoku dziwnych tłumaczeń nie zdążyłem tego obadać. Słuszna korekta.

**Comment by mrownicki** [comment]
Właśnie oto mi chodzi, aby zwykła pani Basia to zrozumiała. 
2 pierwsze lepsze osoby, które są obeznane w miarę dobrze w posługiwaniu się cmsami.
Hej. Proces pracy z czym Ci się to kojarzy na stronie internetowej?
1) Zależy czego dotyczy strona 😛 na przykład Kolejność czynności, jakie trzeba wykonać, żeby zainstalować Joomla
2) Bo jak dla mnie byłby to harmonogram wdrażania zmian czy prowadzenia portalu

A co jakbym Ci powiedział, że dotyczy to Workflow - przepływu pracy?
1)to coś jak ISO np. w Urzędzie - opis i kolejność procesów dot. danej czynności
2) Dzielenie się zadaniami kolejkowanie no i harmonogram pracy tak jak mówiłem. Przyznam się że ja to też nie do końca czuję ten workflow

Jak widać obie, mimo iż mają wiedze bez naprowadzania nie są w stanie wywnioskować konkretnego działania. 
Dla mnie też proces pracy nie kojarzy się z tym co robi całe rozszerzenie.

Dlatego poddaje to pod wątpliwość, iż dobrze zostało wybrane. 
Patrze też pod kontem jak to później trzeba będzie tłumaczyć ludziom, aby załapali za 1 razem.

Bo teraz to będzie wyglądać mniej więcej tak.
Tutaj jest proces pracy, a w tym procesie stworzycie nowe procesy, w których to procesy będą odpowiadać za proces publikacji kolejnych "etapów"/"procesów" (w zależności od tłumaczenia) gdzie dany artykuł będzie w kolejce procesowania. Chyba jakoś tak to będzie wyglądać :)  

Więc nie wiem, czy proces pracy czy przepływ pracy są optymalne. 
Może ktoś z tłumaczy się jeszcze wypowie na ten temat jak oni to widzą i czują.

**Comment by zwiastunsw** [comment]
Marcinie, z tym się będzie kojarzyć, z czym się ktoś spotka, zapozna. To jest nowy komponent. To czy nazwiemy go proces pracy, tryb pracy redakcji, organizacja pracy redakcji, tok pracy itp. nie ma zbyt dużego znaczenia. Wszystkie te zwroty opisują dokładnie to samo, co Ty być może nazwałbyś przepływem pracy. 
Niektórych rzeczy za pierwszym razem się nie złapie. Przesiedziałem ze 4 godziny nad tłumaczeniem i poprawianiem przykładowych danych, w których zastosowano tok pracy/proces pracy/organizację pracy/nawet tryb pracy. Każdy równie dobrze pasuje. Gorzej jest w kontekście: Etapy trybu pracy? Można na upartego znieść, ale nie brzmi to najlepiej. Etapy organizacji pracy czy etapy procesu pracy, czy nawet etapy toku pracy - jest OK. Gdy przyjdzie odmieniać "Procesy pracy" mamy "procesy pracy", procesom pracy", itd. - jest OK. Ale z organizacją już gorzej: Powiesz o dwóch "organizacjach pracy"? Raczej nie powiesz. Czego najpewniej użyjesz: "dwa toki pracy", "dwóch toków pracy" czy raczej "dwa procesy pracy", "dwóch procesów pracy"? Co brzmi lepiej "Rozważaliśmy dwa toki pracy" czy "rozważaliśmy dwa procesy pracy". A może jeszcze lepiej będzie "dwa workfloły" albo "trzech workflowów".
Ja też nie wiem, czy "procesy pracy" są optymalne. Na pewno jasno i zrozumiale definiują to, czym zarządzać będziemy w Joomla za pomocą nowego komponentu autorstwa mojego dobrego kolegi.
A co do głosowania i możliwości wypowiedzenia się społeczności. Miałeś sporo do czynienia z Crowdinem. Tam jest doskonałe narzędzie do sugerowania lepszych tłumaczeń. Popatrzyłeś, jak często to narzędzie do głosownia zostało użyte.
Od co najmniej 3 lat co jakiś czas dopraszam się społeczności, by ktoś zechciał przejąć odpowiedzialność za koordynacje tłumaczeń. Jak dotąd bezskutecznie. Bo nie jest to łatwe zadanie, Także dlatego, że czasem trzeba podejmować decyzje wbrew różnym mniej lub bardziej oryginalnym pomysłom, czasem można się narazić na śmieszność, czasem na ostrą krytykę. Pamiętasz być może "mlaśnięcie" którym się zapisał w historii polskiej informatyki jeden z wybitnych polskich profesorów. Ale miał tę odwagę, by tworzyć polski język informatyki. Mam tę satysfakcję, że i Joomla ma swój skromny, ale jednak, udział w tworzeniu  języka informatyki.  
Taka jest rola koordynatora tłumaczeń. I nawet jeśli po 15 latach od rozstrzygnięcia jak coś tłumaczyć, gdy ktoś zaproponuje, by "unautorised links" przetłumaczyć na "nieautoryzowane linki", koordynator to wykryje i nada właściwy kształt. Bo "nieautoryzowane linki" nie znaczy po polsku nic, a "Pokaż łącza wszystkim" jest jasne i zrozumiałe.
