### ISSUE TITLE
Com_search - brak tłumaczenia w opcjach

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#19]
### Co trzeba zmienić/skorygować?
Całość nie jest przetłumaczona w opcjach

### Jakie tłumaczenie byłoby lepsze
Wydaje mi się, że na Corwdin było to przetłumaczone.

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
![image](https://user-images.githubusercontent.com/28987360/131394919-3d1c2e37-32fb-46ce-9d36-427c027a8400.png)

System/Konfiguracja
### Wersja Joomla! i wersja polskiego pakietu językowego
pl-PL_joomla_lang_full_4.0.2v2

**Comment by zwiastunsw** [comment]
nie  mam błędu, być może dlatego, że zostało to poprawione

**Comment by mrownicki** [comment]
Rozumiem, trochę dziwne, bo to nie instalacja po migracyjna tylko czysta 4 z tym, że od wczesnych etapów alfa. 
To oznacza jedno trzeba zainstalować świeża ;)

**Comment by mrownicki** [comment]
Potwierdzam problem nie występuje na świeżej instalacji.

**Comment by wojsmol** [comment]
Problem starych instalacji zostanie rozwiązany w Joomla! 4.0.3 https://github.com/joomla/joomla-cms/pull/35483
