### ISSUE TITLE
Literówka w COM_CONFIG_FIELD_VALUE_SYSTEM_DEFAULT

### ISSUE THREAD

**Issue by Rogackis** [JoomlaPolska/jezyk-J4#21]
### Co trzeba zmienić/skorygować?

COM_CONFIG_FIELD_VALUE_SYSTEM_DEFAULT="Domyślne systeemu"

### Jakie tłumaczenie byłoby lepsze

COM_CONFIG_FIELD_VALUE_SYSTEM_DEFAULT="Domyślne systemu"

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![literowka](https://user-images.githubusercontent.com/13894174/131409124-6df50f0a-4ad5-4d68-b879-7a1bcda50e63.jpg)

### Wersja Joomla! i wersja polskiego pakietu językowego

Aktualnie zainstalowana wersja Joomla! to "‎4.0.2" ‎4.0.2
Aktualnie zainstalowana wersja tłumaczenia to Polski (PL) 4.0.3

### Dodatkowe informacje

Po ostatnich poprawkach wkradła się literówka

**Comment by zwiastunsw** [comment]
thx
