### ISSUE TITLE
Weblate jako łącznik git i interfejsu dla tłumaczy

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#219]
Pisałem do Wojtka, ale nie dał mi odpowiedzi więc pisze tutaj.

Ponieważ tłumaczenie na GITHUBIE nie jest przyjazne! 

Zaproponowałem https://weblate.org/pl/download/  jako rozwiązanie, które łączy githuba i normalne tłumaczenie ;) 
Doc. jak to działa z gitem https://docs.weblate.org/en/latest/vcs.html?highlight=github#git

Tłumaczenie czy poprawki można łatwo wprowadzać i pushować do githuba, ale ma to znacznie przyjazny interface i nie trzeba się bawić w tworzenie osobnych gałęzi potem to mergować szukać, podmieniać po plikach.

Jestem jedną osobą, która przez ostatnie kilka lat w zasadzie promuje Joomla. Pisze nagrywa video o niej dla ogółu. Tak, aby, jak najwięcej osób się dowiedziało.  WCAG, które jest promowane przez lepszyweb jest równie ważne!  To tylko jedna gałąź, która jest w Joomla.  Ktoś tam od czasu do czasu napisze artykuł jak djki ale zazwyczaj po angielsku i promując swoje rozwiązania. Oni problemu nie mają, bo mają język en wiec zawsze są na czasie.

Więc również zależy mi na tłumaczeniu.. oraz jakości czy czasie wydania tego tłumaczenie. aby nie było rozjazdu. Względem tego, co pisze i nagrywam. Bo jest to w interesie wszystkich i szeroko pojętej promocji samego cms.

Nie zawsze jest czas na "tłumaczenie" ale z mojej perspektywy im wygodniejsze narządzenie, tym łatwiej:
a) zachęcić kogoś do pomocy. 
b) robić wydania na czas.
c) wprowadzać proste poprawki czy literówki

Nikt na githubie nie chce tłumaczyć, bo jest to zbyt SKOMPLIKOWANE! Cóż z tego, że Wojtek pokazał mi co i jak wystarczy 2 tygodnie przerwy i już człowiek zapomina.

Weblate pozwala połączyć oba systemy git i przyjazny interface. 
Więc panowie pochylcie się nad tym rozwiązaniem. Nad wszystkim będzie kontrola tak jak jest do tej pory.
Chce pomagać, ale git mnie męczy i zniechęca.

Liczę na odzew i rozsądną dyskusję.
Dajcie znać co o tym myślicie :)

**Comment by Valdnet** [comment]
Czy tłumaczeniem Joomli na język polski zajmują się tylko 3 osoby? Jeśli tak, to jest to za mała grupa tłumaczy, aby te tłumaczenie było w dobrej jakości i zawsze na czas.

Popieram @mrownicki jak najbardziej. Należy skorzystać z gotowych portali do tłumaczeń. Obecnie czynnie udzielam się na Transifexie w Społeczności Nextcloud jako koordynator i mogę powiedzieć, że tłumaczenia są bardzo dobrej jakości, które są synchronizowane przez bota raz na dzień. Zawsze nowe wersje Nextcloud wydawane są z najnowszymi tłumaczeniami.

To co dzieje się w Joomli, to jest to lekką porażką, z tego tytułu jak już wspomniał @mrownicki tłumaczenie w GitHubie nie jest wygodne, a wręcz trudne. Rozumiem tłumaczenia ciągów w plikach .js, .json lub .xml, ale w plikach .ini, gdzie nie pojawiają się ciągi tekstowe w języku angielskim, to już totalna porażka 😬. Tłumacze nawet nie wiedzą, czy są dodane nowe ciągi tekstowe w języku angielskim w źródle mastera Joomli.

Dodam jeszcze, że tłumaczenia są słabej jakości pod tym względem, że nie są pełne, nie są spójne np. „email” z języka angielskiego jest tłumaczony raz jako „e-mail”, a raz jako „poczta elektroniczna”, a już nie wspomnę już tłumaczenie, które występuje jako „list elektroniczny” :scream:. Drugi przykład, to co zauważyłem, że np: „username” jest tłumaczony raz jako „nazwa użytkownika”, co jest poprawne, w następnym ciągu tekstowym jest przetłumaczony jako „imię i nazwisko”, a w następnym jako „nazwa”. Panowie tłumacze, to jest wielka porażka, obudźcie się. Tak prowadzone tłumaczenie nigdy nie będzie doskonałe.

Całkowicie zirytowało mnie to, jak zainstalowałem nową wersję tłumaczenia 4.1.5v1. Tak jak szybko zainstalowałem, tak szybko odinstalowałem z powodu takiego, że tłumaczenie miało być ulepszone i przetłumaczone te ciągi tekstowe, które jeszcze nie były, to okazało się, że pojawiły się niektóre ciągi tekstowe ponownie w języku angielskim.

Mogę jeszcze tak długo wymieniać, ale w ten sposób nigdy nie osiągniemy celu, czyli dobrego tłumaczenia w języku polskim. I tu należałoby skontaktować się w tej sprawie z twórcami Joomla, aby wszyscy tłumacze różnych języków byli w jednej społeczności, w której powinni sobie nawzajem pomagać np. w zgłaszaniu problemów i błędów oraz poprawianiu ich w oryginalnych ciągach tekstowych.

PS: Ale dziwnie pisze się po polsku na GitHubie 😁.

**Comment by mrownicki** [comment]
@Valdnet 
Niektóre frazy są zaszłością pewnie i nie było to łączone. Na Githubie ciężko to wyłapać, gdy ma się X plików. 
Nie da się też podyskutować o frazach czy wywołać kogoś do wspólnej dyskusji. 

Tłumaczenie jest, jakie jest teraz, póki nie będzie to przyjaźniejsze to ciężko coś konsolidować w nazewnictwie. 
Ja tu tylko się udzielam i wskazuje rozwiązania, aby wilk był syty i owca cała ;) 

Kilka osób tłumaczyło w tym i ja do wersji v4, która została przegrana z v3. 
Testowanie tłumaczenie też jest ważne, bo czasami fraza w pliku ma się średnio do tego, co dana funkcja robi.

**Comment by Valdnet** [comment]
> Testowanie tłumaczenie też jest ważne, bo czasami fraza w pliku ma się średnio do tego, co dana funkcja robi.

Jeśli tłumacz nie wie do czego odnosi się ciąg tekstowy i w jakiej formie go przetłumaczyć, to należy zajrzeć do kodu źródłowego aplikacji i po kodzie rozpoznać, czy dotyczy jakiejś funkcji, czy ustawień, czy jest to może opis przycisku. Tak to robię przynajmniej ja. Dodatkowo przetestowanie tłumaczeń już w samej Joomli tak jak mówisz.

> Na Githubie ciężko to wyłapać, gdy ma się X plików.
> Nie da się też podyskutować o frazach czy wywołać kogoś do wspólnej dyskusji.

I tu właśnie potrzebny jest jeden z portali do tłumaczeń 😁.

**Comment by zwiastunsw** [comment]
Kilka kwestii, poczynając od zasadniczej. Nie rozwiąże to problemów, jakie mamy i nie posunie tłumaczenia do przodu, ale może pozwoli spokojniej podchodzić do sprawy organizacji tłumaczenia. 

1. **Zaangażowanie społeczności w tłumaczenia**: Łatwo się formułuje tezy typu: "...tylko 3 osoby? Jeśli tak, to jest to za mała grupa tłumaczy". Na przestrzeni 18 lat zaangażowanie w tłumaczenie nieco większego grona niż 1-4 osoby zdarzyło się dwa razy. Raz dla Joomla 3, gdy imiennie zwróciłem się do zaangażowanych wówczas w różne działania osób o przygotowanie tłumaczeń konkretnych plików. Drugi raz - dla Joomla 4 - tu szacunkowo około 95-98% pracy wykonały 4 osoby. Choć bardzo i ceniłem, i doceniałem każdy, nawet najdrobniejszy wkład, to fakty są, jakie są. Można je nawet zweryfikować. Ślady pracy nad tłumaczeniem dla J3 są wciąż na naszym forum, statystyki wkładu wolontariuszy na Crowdinie można sobie odtworzyć.
Dodać trzeba do tego, że: 

  - Zanim powstała jakakolwiek platforma umożliwiająca udział społeczności w tłumaczeniach, już w 2006 czy 2007 roku polska społeczność miała taką platformę i dodatkowo forum do dyskusji nad tłumaczeniami ciągów językowych. Platformę do tłumaczeń stworzył nam, że przypomnę, Artur Moskała 'Stone', komponent "forum" dyskusyjnego nad słownikiem tłumaczeń i ciągami językowymi, w którym znalazło się wówczas ponad 3000 propozycji (dziś to się może wydawać niewiele, ale to był 2007 rok) opracowaliśmy z Michałem Sobkowiakiem 'Vikingiem'. Oprócz mnie i Vikinga i czasem Rybika nie przypominam sobie, by ktoś jeszcze wówczas do tej rozmowy się włączył (na forach mieliśmy wówczas około 20 000 odwiedzających i korzystających ze wsparcia). Skutek/efekt: Mnóstwo włożonej pracy, a tłumaczenie jak robiło kilka osób (wówczas to był Stone, Viking, Dylek, Josh i ja, tak robiło kilka osób.

  - Gdy otwarły się możliwości tłumaczenia na platformie Crowdin, z inicjatywy i głównie staraniem 'Yilda', który życzył sobie, by nie ujawniać jego danych, przenieśliśmy  tłumaczenie na tę platformę.  Jak pisałem wyżej, można to sprawdzić w statystykach: 85 357 ciągów językowych, ogółem 52 wolontariuszy uczestniczących przez wszystkie lata w tłumaczeniach, w tym dwóch wniosło wkład wielkości 93,3% - yild i ja, pozostałych 50 wolontariuszy 6,7%. 23 osoby wyraziły swoje zdanie w głosowaniach, w tym 9 uczyniło to więcej niż 20 razy, 14 osób w odniesieniu do 2-6 napisów.
Powtórzę raz jeszcze, żeby to dobrze wybrzmiało, każdy - nawet najmniejszy wkład był i jest bardzo cenny. Ale te liczby powyżej mówią same za siebie.

  - Dodajmy do tego, żem w wieku mocno już dojrzałym i  - jeśli chodzi o zapał do działania na rzecz Joomla - mocno wypalonym. Co jakiś czas, od lat co najmniej 5, dopraszam się Szanownej Polskiej Społeczności Joomla o to, by ktoś zechciał przejąć pieczę nad polskim tłumaczeniem Joomla! Przykro, ale nawet echo się nie odzywa.   

  - Choć dałem sobie słowo, że nie będę się zajmował tłumaczeniem J4, dałem się "wciągnąć", bo kilka osób, w tym dwie szczególnie (Marcin, Rado(sław)) - zaangażowały się w przygotowanie tłumaczenia na niedługo przed premierą. Dzięki nim (ale także innym osobom, którym dziękowaliśmy nawet za 1 linię wkładu) udało się to tłumaczenie sfinalizować, choć błędów i niespójności nie udało się do dziś jeszcze wyeliminować. 
Od premiery J4 i wydania języka polskiego dla 4.0 minął już rok. 
Uwagi  i propozycje zmian w ciągu całego minionego roku zgłosiło nie więcej niż 5 osób, w tym 4  w odniesieniu do pojedynczych fraz. Na błąd w pakiecie dla Joomla 4.1.5 wydanym z opóźnieniem przed dwoma tygodniami  zareagowała 1 osoba tuż przed wydaniem 4.2.0, dzięki czemu drobny, ale uciążliwy błąd (w dwóch liniach), nie został w 4.2.0 powielony.
Do zgłoszenia problemu nie jest potrzebna żadna specjalna platforma - można to było zrobić gdziekolwiek. 

To tyle w kwestii udziału społeczności. Oczywiście, platforma, na jakiej prowadzi się tłumaczenia, może być mniej i bardziej przyjazna, mniej i bardziej wygodna. Ale to nie platforma decyduje o angażowaniu się społeczności w tłumaczenie. Mimo ogromnej wiary w to, że społeczność i współpraca mogą wiele, swego sceptycyzmu wynikającego z pięciu dziesięcioleci organizowania pracy ochotniczej, raczej się już nie wyzbędę. (I dlatego też chętnie przekażę zadania związane z tłumaczeniem każdemu, kto zagwarantuje, że to pociągnie na w miarę poprawnym poziomie.)  

2. **Walory interfejsu**, czyli o platformie do tłumaczeń. 
Może i Crowdin jest lepszym narzędziem. Dla mnie oznaczał od 2015 roku, gdy się przenieśliśmy na tę platformę), podwójną robotę. W niczym nie pomagał, za to wymagał przeglądania tego, co być może wniosła społeczność, zapewniania spójności tłumaczeń na Crowdinie z tym, co było w pakietach (bo tych się na Crowdinie wygenerować nie dawało albo może to ja nie potrafiłem.) 

  - Kiedy wykonuję lub uzupełniam tłumaczenia bezpośrednio w plikach, mam natychmiastową możliwość zobaczenia efektów na działającym systemie, w konkretnym kontekście.  Crowdin mi tej możliwości nie daje.

  - Wcześniej, przy J3 zespół tłumaczy dostarczał pliki różnicowe dla zaplecza i witryny, dzięki czemu wiadomo było, co, gdzie i jak było zmienione. Odszukanie i naniesienie zmian zajmowało - w porównaniu z czasem, jaki temu samemu zadaniu trzeba było poświęcić na Crowdinie - przysłowiową "chwilę". Przez lata Crowdin trochę dojrzał, ale wciąż analizowanie tego, co się zmieniło, jest uciążliwe i wymagające sporego dodatkowego nakładu czasu i pracy. Tu, na Githubie, pracę wykonuje bot, dostarczając na bieżąco informacji o każdej zmianie w języku, co więcej, w przypadku ciągów poprawianych, pokazuje, co dokładnie i gdzie zostało poprawione. O takich podpowiedziach na Crowdinie można sobie pomarzyć.

  - Z fałszywymi stwierdzeniami dyskutować nie ma nawet co. Nieprawdą jest, że "nie da się podyskutować o frazach czy wywołać kogoś do wspólnej dyskusji". Da się to robić nawet o wiele skuteczniej niż na Crowdinie.  
      
  - Dodam jeszcze, że nie tylko ja się dystansuję od Crowdina (czy nie lubię, jak kto chce).  Dla wielu tłumaczy Joomla (czy zespołów tłumaczy) nie jest to wymarzona platforma.

3. **Jakość tłumaczenia**.
  - Cóż, ocenia się łatwo, doprowadza do dobrej jakości wcale nie tak łatwo. Tylko w minionym miesiącu naniosłem około 100-150 poprawek uspójniających tłumaczenie, eliminujących oczywiste i mniej oczywiste błędy i usterki. Niektóre z nich to  zaszłości (listy, poczta i e-mail tudzież email; choć ten był w pewnym momencie konsekwentnie poprawiony). Inne to efekt prób znalezienia najlepszego polskiego odpowiednika, niekoniecznie trafnych. Wiele wynikło, niestety, z wkładu społeczności oraz crowdinowego bota przy przenoszeniu tłumaczeń z J3 do J4. 

  - Trzeba to wykrywać i poprawiać, samo się nie zrobi. Na pewno nie zrobi się tekstami "Panowie tłumacze, to jest wielka porażka, obudźcie się".  Porażka? Proszę sprawdzić, na ile języków Joomla nie ma aktualnego tłumaczenia.

**Podsumowując**: Moje osobiste zasoby zapału, zaangażowania, czasu, sił, możliwości, ale także i otwartości na zmiany i nowości są, jakie są. I dobrze, że jeszcze jakieś są. Póki nie znajdzie się ktoś, kto w pracę nad tłumaczeniem wejdzie i zechce nią dowodzić oraz będzie miał ku temu kompetencje, poprowadzę to tak, jak potrafię, na ile potrafię i na ile sił mi starczy. Ale nie oczekujcie, proszę, że pozwolę sobie na jakiekolwiek eksperymenty tylko dlatego, że może uda się dzięki temu zaangażować chwilowo 1-2-3 osoby, które dołożą nawet złotą cegiełkę, ale domu budować i utrzymywać nie zechcą.

**Comment by mrownicki** [comment]
@zwiastunsw 
A przejrzałeś działanie tego, co zaproponowałem? 
To się wpieni integruje z gitem wiec nadal w zasadzie dla Twojej pracy nic by się nie zmieniło. Podgląd zmian jest w weblate, aktualną wersję tez będzie mógł zobaczyć, bo to jedno repozytorium.

Abstrahując dla mnie jest problem tłumaczyć przez Git'a wchodząc w każdy plik i nanosząc poprawki pod zgłoszenia przez bota. 
Bot sobie nadal może dodawać tutaj zgłoszenia, bo i tak aktualizuje pliki ini przecież. W Weblate pojawi się po prostu admin.ini że, ze 100% zrobiło się 95% Wchodze w plik i pokazuje co jest do tłumaczenia ;) Mogę zrobić pusha a Ty to możesz sobie sprawdzić, czy nawet jako admin sam robić pushe.

**Comment by zwiastunsw** [comment]
Przejrzałem, wygląda, że jest jak mówisz. Ale platforma jest płatna, co prawda, dla organizacji i opensource jest możliwość korzystania bezpłatnie, ale ponieważ wkrótce fundacja zostanie rozwiązana, nie mogę podejmować żadnych nowych formalnych zobowiązań. Trzeba to dokładniej rozpoznać.

**Comment by mrownicki** [comment]
Można instalować na serwerze bez wsparcia na dedykowanym linuxowym serwerze czy joomla.pl takowym czasem nie dysponuje?
Rozumiem, że jak fundacja zostaje rozwiązana to również joomla.pl zniknie? i wiki etc?

**Comment by zwiastunsw** [comment]
Będziemy się zastanawiać, co z tym zrobić.

**Comment by Valdnet** [comment]
@zwiastunsw Dziękuję za tak treściwy opis historii powstawania tłumaczenia. Przybliżyłeś mi to co się działo wcześniej i teraz.

Powracając do tematu, to tłumaczyć bezpośrednio na GitHubie to trochę przestarzała metoda. Należy jak najszybciej to zmienić wybierając jedną z platform do tłumaczenia lub postawić swoją o czym wspomniał @mrownicki. Tylko w ten sposób ułatwi to tłumaczom w wykonywaniu tłumaczenia dla Joomla.

**Comment by artur-stepien** [comment]
Obecnie tłumaczenie musi przechodzić przez 3 platformy, Crowdin (obowiązek od strony OSM), miejsce do przechowywania czyli GitHub i dodatkowo trzeba jeszcze publikować na downloads.joomla.org (obowiązek od strony OSM). Dodanie 4 platformy nie tylko by nie pomogło ale wydłużyło by i tak już długi proces publikacji. A biorąc pod uwagę ilość osób zaangażowanych w tłumaczenie wynikiem mogła by być sytuacja z tłumaczeniem Joomla! 5. Na chwilę obecną zamknę to zgłoszenie, bo jest nierealnym dalsze komplikowanie i tak skomplikowanego procesu.
