### ISSUE TITLE
Pozycja - moduły

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#22]
### Co trzeba zmienić/skorygować?
COM_MODULES_HEADING_POSITION - Pokaż/Ukryj kolumnę Stanowisko na liście kontaktów.
### Jakie tłumaczenie byłoby lepsze

COM_MODULES_HEADING_POSITION - Pozycja

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
Widok modułów

### Wersja Joomla! i wersja polskiego pakietu językowego
J4.02 i 4.0.2v2

**Comment by wojsmol** [comment]
Było zgłoszone w https://github.com/JoomlaPolska/jezyk-J4/issues/6 i jest poprawione w gałęzi `pakiet-4.0.3` od 4 dni.

**Comment by mrownicki** [comment]
> Było zgłoszone w #6 i jest poprawione w gałęzi [pakiet-4.0.3](https://github.com/JoomlaPolska/jezyk-J4/archive/refs/heads/pakiet-4.0.3.zip) od 4 dni.

Wszystko super , ale w realese dostępny jest 4.0.2v2 a nie 4.0.3 ... Tak każdy może zgłaszać ten sam błąd, gdyż pracuje na starej wersji ;)

**Comment by zwiastunsw** [comment]
My na to nie poradzimy.  Dlatego dostałeś informację, że błąd jest już naprawiony, a problem został zamknięty jako rozwiązany. Osoby, które chcą aktywniej pracować nad doskonaleniem języka mogą sklonować repozytorium i pracować nad zawsze najaktualniejszą wersją językową. Ja synchronizuje najpierw swoją lokalną kopię z tym, co jest w najnowszej gałęzi, nad którą pracujemy, następnie przekopiowuje pliki do instalacji Joomla, na której sprawdzam kontekst. Gdy przygotuję jakiś zestaw poprawek, przerzucam pliki z powrotem do kopii z Githuba, wysyłam poprawki wynikające ze zgłoszeń i własne. 
Gdy ktoś zgłosi PR, jak ostatnio Zofiabot, zanim zrobię cokolwiek u siebie, musze najpierw zsynchronizować wersje.
Niestety, nie jest to tak "hop-siup" jak by się mogło wydawać :)
Zachęcam do metody działania opisanej pokrótce we [wskazówkach do współpracy](.github/CONTRIBUTING.md) i zacznij od pierwszego pytania/zgłoszenia problemu.

**Comment by zwiastunsw** [comment]
PS. Otwieram chwilowo problem, bo ta rozmowa może być przydatna dla innych współpracowników

**Comment by mrownicki** [comment]
Nie wiem kto wpadł na pomysł, aby tłumaczyć na githubie. Być może tak było zawsze. Ale github to nie jest narzędziem przeznaczonym przecież do tłumaczeń, ani dedykowanym. Szczególnie, że trzeba się "nauczyć" owej obsługi co zniechęca mnie i zapewne wielu innych.

Może po prostu zrobić harmonogram jak już musi być używany Github do tego.
1) Nie zamykać Issue np. Do czwartku, a w piątek robić nową wersję, która będzie dostępna w realise jako aktualna zawsze. Bo jeśli ty robisz merge i wypychacz nową paczkę. Więc możesz to ustalić sobie pod siebie. W jeden dzień zamykamy X issue z całego tygodnia i generujemy nową paczkę na nowy tydzień. Taki swoisty cykl. 

Nawet jeśli sobie będę synchronizował tłumaczenie i je tłumaczyć "po swojemu" i commitował to dodatkowo dojdzie CI robota lub komuś, abym to wszystkie zmiany przejrzał. Albo je zatwierdził albo nie.
Wówczas ja poświęcił nie potrzebnie czas na "swoje" tłumaczenie, z którym możesz się nie zgadzać. A Ty poświęcisz czas na niezatwierdzanie. 

Czemu nie jest używany Corwid do tłumaczenia skoro Joomla,org tam umieszcza pliki? Jest jakiś konkretny powód, iż zostało to przeniesione tutaj?

**Comment by zwiastunsw** [comment]
Dla podstawowej pracy nad tłumaczeniem Crowdin jest z pewnością bardzo dobrym narzędziem, głównie ze względu na bazę tłumaczeń, podpowiedzi. Dla utrzymywania i poprawek tłumaczenia jest, niestety, uciążliwy, powoduje znaczne obciążenie czasowe. Trudno mi to oceniać w sposób precyzyjny, ale korzystanie z Crowdin kosztowało 3-4 razy więcej czasu na przygotowanie kolejnej paczki językowej, niż tradycyjna metoda w Notatniku czy nawet z komponentem Localise, który pozwalał wychwycić braki. 
Github jest narzędziem dedykowanym do pracy zespołowej nad każdym kodem, także językowym. Oczywiście, nie udostępnia aż tak specjalistycznych narzędzi, jak Crowdin, jeśli chodzi o samo tłumaczenie, ale jest o wiele bardziej wydajnym narzędziem  do pracy zespołowej nad rozwijaniem, doskonaleniem, uzgadnianiem, synchronizacją, historią wersji. 
A trudność używania? Każde narzędzie ma swoją krzywą uczenia się. Mnie opanowywanie podstawowych funkcjonalności Crowdina zajęło lata całe, choć w miarę pojętny jestem. A i tak pewno jeszcze nie znam wszystkich niuansów. Od strony użytkownika Crowdin może się wydawać łatwiejszy i wygodniejszy, od strony zarządzania tłumaczeniem nie jest.
