### ISSUE TITLE
Wielokropek

### ISSUE THREAD

**Issue by Valdnet** [JoomlaPolska/jezyk-J4#226]
W tłumaczeniu występują trzy kropki, co jest błędem w pisowni. Należy stosować znak wielokropka w tej postaci `…`.

Problem zgłoszony również w [repozytorium Joomla](https://github.com/joomla/joomla-cms/issues/38630), gdzie występuje ten sam błąd.

**Comment by zwiastunsw** [comment]
W tłumaczeniu to pewno bywa różnie. Oczywiście, masz rajcę.

**Comment by zwiastunsw** [comment]
rozwiązane we wszystkich plikach

**Comment by Valdnet** [comment]
Dzięki 😉. Bardzo dobra robota 👍.

**Comment by zwiastunsw** [comment]
w jednym pliku trafiła się literówka :)

**Comment by Valdnet** [comment]
> w jednym pliku trafiła się literówka :)

Super, że wyłapałeś ją 🥇. Dodatkowo zauważyłem lekkie poprawki w tłumaczeniu 😉.
