### ISSUE TITLE
Kilka poprawek

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#312]
Hej
Wybaczcie, że bez ciągów znaków, ale brak mi czasu... 
Poprawki tłumaczenia:

**Mamy dubel w nazwie (Listowanie dodatków)**

Usługi sieciowe - prywatność  (tu jest dubel)
Usługi sieciowe - przekierowania

Skrót - srawdzanie wersji PHP

Brakuje p sprawdzenie

**Rozszerzenia OPCJE:**

Kontakty/Artykuły/Użytkownicy/Zakładki - Integracja
Edycja pól dodatkowych 
To nie jest edycja przełączenie powoduje, że w menu pojawiają się "Pola dodatkowe" etc.
Więc to powinno się nazywać **"Włącz pola dodatkowe"**

Po aktualizacji do J4 i jeśli ktoś miał zakładki to brakuje w menu tłumaczenia
Pola dodatkowe
Grupy pól dodatkowych

**Kontakt**
Kategorie/Pola dodatkowe
Rozwijane menu u góry
Kontakt, Poczta, Kategoria

Poczta do zmiany to jest Formularz i tego tyczą się pola.

Pozdrawiam.

**Comment by zwiastunsw** [comment]
ok thx
