### ISSUE TITLE
Edytor - CodeMirror - zaplecze - przycisk

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#33]
### Co trzeba zmienić/skorygować?
Jak przełączymy na Edytor - Code Mirror to w artykułach / modułach mamy na dole przyciski i jeden z nich się zwie.
**Przedrostek nazwy obrazka**

### Jakie tłumaczenie byłoby lepsze
Manager mediów lub Media  lub Dodaj media

Joomla 4 nie obsługuje już tylko obrazków, ale i inne pliki więc przydałoby się to uściślić. Sugeruje opcje 3 Dodaj media

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
![media](https://user-images.githubusercontent.com/28987360/134053476-6b543314-a0ff-497c-b50c-c7054a637e57.png)

### Wersja Joomla! i wersja polskiego pakietu językowego
Oficjalnie dostępne.

**Comment by mrownicki** [comment]
Ten problem powinien się rozwiązać z tym zgłoszeniem. 
https://github.com/JoomlaPolska/jezyk-J4/issues/43
Ale nie testowałem więc jak Panowie znajdziecie chwilę to sprawdźcie proszę.

**Comment by zwiastunsw** [comment]
tak, rozwiązał się, dzięki.
