### ISSUE TITLE
Dostosuj szablon

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#35]
### Co trzeba zmienić/skorygować?
Wpisz adres e-mail tego użytkownika.

### Jakie tłumaczenie byłoby lepsze
Edytor plików

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![nadpisywanie](https://user-images.githubusercontent.com/28987360/134183486-f3c787fd-6cd8-4d9d-840f-6897a3000397.png)
### Wersja Joomla! i wersja polskiego pakietu językowego
Obecna dostępna wersja.

**Comment by zwiastunsw** [comment]
Dziękuje, poprawione, znajdzie się w najbliższym PR
