### ISSUE TITLE
Wyszukiwarka

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#39]
### Co trzeba zmienić/skorygować?
Brakuje tłumaczenie czy o to wyrażenie chodziło.

Entering this and that into the search form will return results containing both "this" and "that".

Here are a few examples of how you can use the search feature:

Entering this not that into the search form will return results containing "this" and not "that".

Entering this or that into the search form will return results containing either "this" or "that".

Search results can also be filtered using a variety of criteria. Select one or more filters below to get started.

Entering "this and that" (with quotes) into the search form will return results containing the exact phrase "this and that".

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![wyszukiwarka](https://user-images.githubusercontent.com/28987360/134939135-d6442f73-5b3b-4468-9351-0b7c0fbb5c84.png)
### Wersja Joomla! i wersja polskiego pakietu językowego
Obecna dostępna

**Comment by zwiastunsw** [comment]
Te teksty są przetłumaczone, tłumaczenie działa (w rzeczywistości jest drobny błąd w tłumaczeniu jednego ciągu ("To nie tamto" - dwa razy jest powtórzone "to oraz tamto")  - poprawimy w następnym wydaniu.

**Comment by mrownicki** [comment]
Hmm.. wygląda na to, że to być może bug samej Joomla. 
Na Casiopei pokazuje po PL na HU3 po EN, mimo że język frontu to PL. 
Chyba że jest nadpisany na sztywno widok., ale to byłoby bez sensu. 
Muszę to w takim razie sprawdzić.
