### ISSUE TITLE
Konfiguracja globalna + opcje rejestracji

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#40]
### Co trzeba zmienić/skorygować?
Opcje rejestracji 
Tab, jak i pierwszy nagłówek (screen)

### Jakie tłumaczenie byłoby lepsze
Opcje logów

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
![konfiguracja-globalna](https://user-images.githubusercontent.com/28987360/135240538-e2469c06-f522-4c8e-8285-e49c98605fc6.png)

### Wersja Joomla! i wersja polskiego pakietu językowego
Obecna 4.0.3 wraz z oficjalnym językiem

### Dodatkowe informacje
Opcja rejestracji jest myląca bo może być brana jako "opcje rejestracji użytkowników" Więc proponuję zmianę na Opcje logów

**Comment by zwiastunsw** [comment]
Opcje "logowania" będą tak samo "mylące", jak opcje rejestracji.

**Comment by mrownicki** [comment]
Jak nazwiesz to rejestracja to nie będzie wiadomo, o co chodzi.
Samo rejestracja będzie się kojarzyło z rejestrowaniem użytkowników, bo jest naturalny tok myślenia osoby nieobeznanej.

Co do słownika informatycznego. Przepraszam może i taki istnieje, ale kompletnie nie jest w obiegu w branży IT.
Proszę podejdź do tego życiowo, tak aby nagłówek sugerował co tam znajdziemy.

Logging in to jest zalogowano w systemie / logowanie
Logging out to nie żadne wyrejestrowanie.. nikt takiego słownictwa nie używa w IT wylogowano z systemu / wylogowano. 

Branża IT jest dynamiczna i pewne przywary są używane i kieruje się zasadą, że ma być wiadomo, o co chodzi, a nie według poprawnej polszczyzny. Kiedy się da stosować to się stosuje poprawne formy. 
Opis opcji ma odpowiadać za to, co robi. 

Dlatego "Opcje logów" sa jednoznaczne, że chodzi o logowanie zdarzeń.

Jak chcesz użyć koniecznie słowa rejestracja to musisz to doprecyzować jak Rejestracja logów. Wówczas będzie wiadomo, że nie chodzi o rejestracje użytkowników, a o rejestrowanie zdarzeń w plikach log

Ps. kiedy planowana jest aktualizacja języka?

**Comment by zwiastunsw** [comment]
1. Możliwe, że "tok myślenia osoby nieobeznanej" spowoduje, iż rejestracja będzie się jej kojarzyła tylko z rejestracją użytkowników. Mnie też się tak często kojarzy, ale również w podobnym znaczeniu np. z rejestracją do lekarza. Ale skąd przypuszczenie, że "logowanie" będzie się takiej osobie kojarzyło z zapisywaniem do dzienników, czy jak pewno wolałbyś "logów"?
2. Nie wiem, czy wiesz, jak powstają słowniki, w tym także informatyczny. Ale podstawą nie są jakieś wymysły-pomysły czcigodnych panów profesorów, tylko badanie rzeczywistości językowej. I jeśli czegoś się w języku nie używa albo już nie używa to słowniki takie kwestie sygnalizują.  Teza, że "nikt tak nie mówi" nie jest  prawdziwa, łatwa do obalenia, wystarczy wskazać jedną  osobę, która tak mówi. Ale, żeby nie było: zobacz poniższy zrzut ekranu:
![loggingout](https://user-images.githubusercontent.com/29527200/135645198-cc40f270-358d-4678-8ad2-3556ae32ffa8.jpg)
3. Odpowiedzialność tłumacza to jest również odpowiedzialność za poprawną polszczyznę. "Opcje logów" to żargon informatyczny, a nie poprawny język. Nie ma też co doprecyzowywać, że to "rejestracja logów", bo - pomijając kwestie poprawności językowej, to, o co chodzi jest zrozumiałe, z treści okna. 
4. Aktualizacja języka - po aktualizacji Joomla, chyba że znajdzie się więcej problemów, zwłaszcza krytycznych.

**Comment by mrownicki** [comment]
Pisałem o polskim odpowiedniku, a nie angielskim.
Nigdzie nie stwierdzałem, że to wymysły.. i proszę o nieprzypisywanie mi słów, których nie napisałem. Słownik słownikiem życie jest życie a całe swoje zawodowe życie jestem związany z branżą IT. 
Zarówno w tłumaczeniach, jak i rozmowach używa się owego "żargonu" bo jest on zrozumiały dla ludzi z branży IT...

W jakim celu jest. "Jakie tłumaczenie byłoby lepsze" jeśli o wszystkim Ty decydujesz. Wybacz, ale wygląda na to, że osoby zgaszające problemy mają odwalić czarną robotę i nie mają na nic wpływu. Jeśli według Ciebie twoja racja jest jedyną i służą racją. Wolisz poświęcić czas na udowodnienie swoich tez i postawienie ostatniej kropi. 
Nie na tym polega współpraca i kolaboracja. A potem się dziwisz, że nikt nie pomaga, bo z takim podejściem ciężko jest pomagać. Na prawdę, jeśli nie ma kompromisu i z góry jest przesadzone jak ma być.

Ja mam naprawdę wiele ciekawszych zająć niż wrzucanie błędów tutaj...

**Comment by zwiastunsw** [comment]
1. Rozumiem, że chodzi ci o "wylogowanie". Ok.  Źle Cię zrozumiałem. Ale to nie  zmienia istoty rzeczy. Użyte w tym kontekście postulowane przez Ciebie słowo "logowanie" będzie przez wielu rozumiane jako logowanie do systemu, a nie rejestrowanie zdarzeń w dziennikach (logach).
2. Niczego Ci nie przypisuję. Wyjaśniam jedynie, że źródłem tego, co jest w słownikach jest życie, praktyka używania języka, a nie jakieś teorie. 
3. To nieprawda, że "Zarówno w tłumaczeniach, jak i w rozmowach używa się owego "żargonu", bo jest on zrozumiały dla ludzi z branży IT...".  Oprogramowanie komputerowe rzadko kiedy jest przeznaczone tylko dla ludzi z branży informatycznej. Joomla też nie jest przeznaczony tylko dla tej grupy zawodowej. I dlatego zarówno stosowanie terminów specjalistycznych, jak i żargonu powinno być ograniczone do niezbędnego minimum. 
4. Opcja "Jakie tłumaczenie byłoby lepsze" jest dokładnie po to, po co jest - aby zgłosić swoje pomysły, bo nikt nie ma recepty na najlepsze. Z najnowszych przykładów: sugestie tłumaczenia "workflow". W tłumaczeniu mamy "proces pracy", a nie proponowane przeze mnie "tok pracy". 
5. Ja współpracę rozumiem, jako pracę wspólną z innymi, w której każdy daje z siebie, co dać może i robi to, na najlepiej, jak może.  Trudno dyskutować ogólnikami, bo to niczego nie wnosi, a nie prowadziłem jakiegoś rejestru, ale to, że kilkanaście osób zaangażowało się w tłumaczenie, w tym szczególnie i Ty, i Radek, a w przygotowanie systemu Wojtek,  to to tłumaczenie po pierwsze jest (zobacz, ilu tłumaczeń jeszcze nie ma), a po drugie jest lepsze, niż by je wykonała jedna osoba. Nie mówię już o tym, że ileś korekt tego, co było w Joomla 3, zostało wprowadzonych dzięki temu, że zostały zgłoszone inne propozycje, ujęcia, także - w wielu przypadkach - przez Ciebie.

I na koniec, uwierz mi, że mam o wiele bardziej pochłaniające mnie i satysfakcjonujące zajęcia, niż zajmowanie się językiem polskim dla Joomla, na które z trudem znajduję czas. Łatwiej byłoby mi tez powiedzieć nieraz "będzie tak bo ja tak chcę" albo "ja tu rządzę", niż dyskutować, wyjaśniać, dlaczego tak, a nie inaczej, prowadzić konsultacje z innymi.
