### ISSUE TITLE
Konfiguracja globalna + uprawnienia

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#41]
### Co trzeba zmienić/skorygować?
Uprawnienia modułu

Tab i pierwszy nagłówek.

### Jakie tłumaczenie byłoby lepsze
Uprawnienia

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![konfiguracja-uprawnienia](https://user-images.githubusercontent.com/28987360/135241552-0d4af106-d16c-4e82-9d97-42ad427b918c.png)
### Wersja Joomla! i wersja polskiego pakietu językowego
4.0.3 + oficjalne tłumaczenie

### Dodatkowe informacje
W J3 mamy uprawnienia bez "modułu" . Może to być mylące, gdy nagłówek zawiera nazwę modułu.

**Comment by zwiastunsw** [comment]
Dziękuję, oczywisty błąd (dzięki Crowdinowi!)
