### ISSUE TITLE
Media meneger - widok listy

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#42]
### Co trzeba zmienić/skorygować?
Użytkownik 
Wybierz klienta

### Jakie tłumaczenie byłoby lepsze
Pliki
Rozmiar

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)

![Opera Zrzut ekranu_2021-10-03_004852_j4 joomlaguru pl](https://user-images.githubusercontent.com/28987360/135733671-b67c2c99-ccba-4a4b-a84a-3cccfdbc5acd.png)
### Wersja Joomla! i wersja polskiego pakietu językowego
4.0.3 - obecna dostepna

**Comment by zwiastunsw** [comment]
Poprawione, przy okazji trochę uspójnione tłumaczenia zaplecza i frontu. Dzięki
