### ISSUE TITLE
Tłumaczenie v5

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#501]
Witam,
Jak wygląda sprawa tłumaczenie v5 czy jest ono brane z cowdin? 
Jeśli tam zostanie dokonana zmiana jest to brane pod uwage?

V4.4.0.2
Z tego co pamiętam nie jest brane.
Więc od frontu brakuje "zapisz i zamknij" oraz "zapisz jako kopie"

**Comment by artur-stepien** [comment]
Nie jest już brane bo generowało to więcej problemów niż korzyści, wszelkie zmiany powinny być dokonywane tutaj. Natomiast nadal musimy tam wysyłać zmiany po publikacji ze względu na fakt, że instalator Joomla! tłumaczenia bierze z Crowdina (ale to już jest po stronie publikującego, nie osoby zgłaszającej i ważne jest tylko dla zmian w instalatorze).

A odnośnie ``Zapisz i zamknij`` oraz ``Zapisz jako kopię`` gdzie brakuje dokładnie?

**Comment by wojsmol** [comment]
@artur-stepien @mrownicki Problem z `Zapisz i zamknij` oraz `Zapisz jako kopię` został rozwiązany w https://github.com/JoomlaPolska/jezyk-J4/commit/6da321ffe2ed3d646cfb03bb2aabe5b74ee9e444

**Comment by artur-stepien** [comment]
Czyli można zamknąć
