### ISSUE TITLE
Zmiany nazw przy pulpitach

### ISSUE THREAD

**Issue by mrownicki** [JoomlaPolska/jezyk-J4#62]
### Co trzeba zmienić/skorygować?
COM_CONTENT_DASHBOARD_TITLE
COM_MENUS_DASHBOARD_TITLE
COM_CPANEL_DASHBOARD_COMPONENTS_TITLE
COM_USERS_DASHBOARD_TITLE
### Jakie tłumaczenie byłoby lepsze
Pulpit zarządzanie artykułami  
Pulpit zarządzanie menu
Pulpit zarządzanie komponentami
Pulpit zarządzanie użytkownikami

Ewentualnie powielić nazwy z nadrzędnego menu.
Artykuły
Pozycje menu
Komponenty
Użytkownicy

### Gdzie jest wyświetlany ciąg znaków (witryna/zaplecze)?
(np. zrób zrzut ekranu, podaj ścieżkę względną do ekranu)
![image](https://user-images.githubusercontent.com/28987360/141781034-0c9dd0ad-e709-492b-bc0a-dde83fd3b1cd.png)

### Wersja Joomla! i wersja polskiego pakietu językowego
4.0.4

**Comment by mrownicki** [comment]
@wojsmol czy to już zostało dodane?? Bo widzę, że tłumaczenie stoi... Martwi mnie to. Pogadaj ze Stefanem i serio wymyślcie inny sposób kontrybucji w tłumaczenie. Bo tłumaczenie stoi w miejscu.

**Comment by wojsmol** [comment]
@mrownicki Po następnym wydaniu - dla 4.0.6 - planowanym na weekend - Spróbujemy odpalić budowanie paczek nightly. Bardzo chętnie przyjmiemy pomoc w tłumaczeniu dla 4.0 i 4.1 w formie PR. Jeżeli Stefan się zgodzi to issues tworzone przez bota będą przypisywane też do Ciebie.

**Comment by mrownicki** [comment]
@wojsmol Wojtek ale co mi to da? Oprócz info, że powił się nowy string do tłumaczenia etc. Zauważ, że obsługuje Gita z poziomu przeglądarki ;)

**Comment by zwiastunsw** [comment]
1. Zmieniliśmy zgodnie z sugestią Zarządzanie...

2. Dziękuję za uwagi odnośnie sposobu tłumaczenia, ale to, że momentami "tłumaczenie stoi" nie zależy od sposobu tłumaczenia, tylko od moich możliwości czasowych. Można przyspieszyć, zgłaszając PR, o czym pisał @wojsmol
